version: '3'
services:
  automator_app:
    container_name: automator_app
    build: .
    volumes:
      - ./instagram-scrape:/usr/src/app
    ports:
      # Port for the API service
      - "3000:3000"
      # Port for the Appium server
      - "4723:4723"
    